name: Release
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          export ELECTRON_SKIP_BINARY_DOWNLOAD=1
          npm install
          cd src/webui/FE
          npm install

      - name: Build
        run: |
          npm run build
          npm run build-webui

      - name: Compress dist
        run: |
          
          sudo apt install zip -y
          cd ./dist/
          zip -r ../LLOneBot.zip ./*

      - name: Compress for Windows Cli
        run: |
          mkdir llbot-cli-win-x64
          cd llbot-cli-win-x64
          cp ../dist/使用说明.txt ./
          cp ../dist/更新日志.txt ./
          cp ../dist ./llonebot
          wget https://github.com/linyuchen/PMHQ/releases/latest/download/pmhq-win-x64.zip
          unzip pmhq-win-x64.zip
          rm pmhq-win-x64.zip
          mv pmhq-win-x64.exe llbot.exe
          wget https://github.com/LLOneBot/exe/releases/latest/download/node.exe -O llonebot/node.exe
          # zip -r ../LLOneBot-win-x64.zip ./*
          wget https://github.com/LLOneBot/exe/releases/latest/download/ffmpeg.exe -O llonebot/ffmpeg.exe
          wget https://github.com/LLOneBot/exe/releases/latest/download/ffprobe.exe -O llonebot/ffprobe.exe
          zip -r ../LLBot-cli-win-x64.zip ./*

      - name: Compress for Windows Desktop
        run: |
          mkdir llbot-desktop-win-x64
          mkdir -p bin/llonebot
          cd llbot-desktop-win-x64
          cp ../dist/使用说明.txt ./
          cp ../dist/更新日志.txt ./
          cp ../dist ./bin/llonebot
          wget https://github.com/LLOneBot/Lucky-Lillia-Desktop/releases/latest/download/lucky-lillia-desktop-win-x64.zip
          unzip lucky-lillia-desktop-win-x64.zip
          rm lucky-lillia-desktop-win-x64.zip
          mv lucky-lillia-desktop.exe llbot.exe
          zip -r ../LLBot-Desktop-win-x64.zip ./*

      - name: Compress for Linux CLI x64
        run: |
          mkdir llbot-cli-linux-x64
          cd llbot-cli-linux-x64
          cp ../dist/使用说明.txt ./
          cp ../dist/更新日志.txt ./
          cp ../dist ./llbot
          wget https://github.com/linyuchen/PMHQ/releases/latest/download/pmhq-linux-x64.zip
          unzip pmhq-linux-x64.zip
          rm pmhq-linux-x64.zip
          mv pmhq-linux-x64 llbot
          wget https://github.com/LLOneBot/exe/releases/latest/download/node-linux-x64 -O llbot/node
          cp ../script/start-linux.sh ./start.sh
          zip -r ../LLBot-CLI-linux-x64.zip ./*

      - name: Compress for Linux CLI arm64
        run: |
          mkdir llbot-cli-linux-arm64
          cd llbot-cli-linux-arm64
          cp ../dist/使用说明.txt ./
          cp ../dist/更新日志.txt ./
          cp ../dist ./llbot
          wget https://github.com/linyuchen/PMHQ/releases/latest/download/pmhq-linux-arm64.zip
          unzip pmhq-linux-arm64.zip
          rm pmhq-linux-arm64.zip
          mv pmhq-linux-arm64 llbot
          wget https://github.com/LLOneBot/exe/releases/latest/download/node-linux-arm64 -O llbot/node
          cp ../script/start-linux.sh ./start.sh
          zip -r ../LLBot-CLI-linux-arm64.zip ./*

      - name: Compress for Docker
        run: |
          wget https://raw.githubusercontent.com/linyuchen/PMHQ/refs/heads/main/docker/install-llob.sh -O LLBot-Docker.sh
          

      - name: Extract version from tag
        id: get-version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> "$GITHUB_OUTPUT"

      - name: Generate release body from changelog
        id: changelog
        run: |
          # 取第一个分段
          content="$(awk 'BEGIN{RS="=================";ORS=""} NR==1{print}' doc/更新日志.txt)"
          # 去掉前两行
          body="$(echo "$content" | tail -n +3)"
          # 去除前后空白
          body="$(echo "$body" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')"
          # 输出到 GITHUB_OUTPUT
          echo "BODY<<EOF" >> $GITHUB_OUTPUT
          echo "$body" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: 'LLOneBot.zip, LLBot-Desktop-win-x64.zip, LLBot-CLI-linux-x64.zip, LLBot-CLI-linux-arm64.zip， LLBot-Docker.sh'
          draft: true
          token: ${{ secrets.RELEASE_TOKEN }}
          name: LLOneBot v${{ steps.get-version.outputs.VERSION }}
          body: |
            ${{ steps.changelog.outputs.BODY }}
